# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x.ndim

1

In [4]:
x=np.reshape(x,(2,5))
print(x)
print(x.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
x1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
x2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19]).reshape(2,5)

In [6]:
np.vstack((x1,x2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [7]:
x1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19])
np.vstack((x1,x2))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [8]:
f=np.vstack((x1,x2))
np.ravel(f)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [9]:
np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]).ravel()

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [12]:
x=np.random.randn(25).reshape(5,5)*5
np.array(x)
x=np.square(x)
x

array([[1.28870808e+02, 1.40385731e+02, 1.95752614e+01, 2.69310346e+01,
        2.39304541e+01],
       [5.15048927e+00, 2.71821630e+00, 1.63800335e+01, 9.22537002e+01,
        7.72390206e-01],
       [4.02825379e+01, 1.38198850e+02, 8.45543032e-01, 3.98118522e+01,
        1.46240658e+01],
       [6.46016687e+00, 1.96000641e+01, 3.53937898e+01, 1.33978282e+01,
        2.75398193e+00],
       [6.01795760e-03, 4.08088590e+00, 3.84236558e+01, 2.51446247e+01,
        1.90145133e+01]])

## Question:8

### Create 5x6 an array and find the mean?

In [13]:
x=np.random.randn(25).reshape(5,5)*5
x=np.array(x)
m=np.mean(x)
m

-1.3552520176908893

In [14]:
x

array([[-1.30129659, -3.61820058, -3.49739052,  0.57481579,  1.83975601],
       [-0.09809309, -4.37582097,  0.88384962,  1.7009184 ,  1.2915885 ],
       [-7.2229021 , -1.32673764, -4.71483437,  5.45009108, -5.03626598],
       [-1.67465166, -1.94396749, -1.16240177, -2.52047651,  2.71043686],
       [-9.99344943, -0.14544813, -2.58488646,  3.96216066, -1.07809408]])

## Question:9

### Find the standard deviation of the previous array in Q8?

In [15]:
np.std(x)

3.3799897730172406

## Question:10

### Find the median of the previous array in Q8?

In [16]:
np.median(x)

-1.3012965949930455

## Question:11

### Find the transpose of the previous array in Q8?

In [17]:
x

array([[-1.30129659, -3.61820058, -3.49739052,  0.57481579,  1.83975601],
       [-0.09809309, -4.37582097,  0.88384962,  1.7009184 ,  1.2915885 ],
       [-7.2229021 , -1.32673764, -4.71483437,  5.45009108, -5.03626598],
       [-1.67465166, -1.94396749, -1.16240177, -2.52047651,  2.71043686],
       [-9.99344943, -0.14544813, -2.58488646,  3.96216066, -1.07809408]])

In [18]:
x.T

array([[-1.30129659, -0.09809309, -7.2229021 , -1.67465166, -9.99344943],
       [-3.61820058, -4.37582097, -1.32673764, -1.94396749, -0.14544813],
       [-3.49739052,  0.88384962, -4.71483437, -1.16240177, -2.58488646],
       [ 0.57481579,  1.7009184 ,  5.45009108, -2.52047651,  3.96216066],
       [ 1.83975601,  1.2915885 , -5.03626598,  2.71043686, -1.07809408]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [19]:
x=np.random.randn(16).reshape(4,4)*5
x=np.array(x)
x

array([[-2.84460387,  1.8097089 , -3.24050317,  4.71048939],
       [ 5.09043034, -1.60297851,  4.67245204,  3.39532926],
       [ 4.26850172, -1.972173  ,  3.28047686, -1.84360623],
       [ 2.22295692,  2.96858839, -5.3727855 ,  8.94974222]])

In [20]:
np.diagonal(x)

array([-2.84460387, -1.60297851,  3.28047686,  8.94974222])

In [21]:
np.diagonal(x).sum()

7.782636701448661

## Question:13

### Find the determinant of the previous array in Q12?

In [22]:
x

array([[-2.84460387,  1.8097089 , -3.24050317,  4.71048939],
       [ 5.09043034, -1.60297851,  4.67245204,  3.39532926],
       [ 4.26850172, -1.972173  ,  3.28047686, -1.84360623],
       [ 2.22295692,  2.96858839, -5.3727855 ,  8.94974222]])

In [23]:
x.shape

(4, 4)

In [24]:
np.linalg.det(x)

-91.4618400203139

## Question:14

### Find the 5th and 95th percentile of an array?

In [25]:
x

array([[-2.84460387,  1.8097089 , -3.24050317,  4.71048939],
       [ 5.09043034, -1.60297851,  4.67245204,  3.39532926],
       [ 4.26850172, -1.972173  ,  3.28047686, -1.84360623],
       [ 2.22295692,  2.96858839, -5.3727855 ,  8.94974222]])

In [26]:
print("5th percentile",np.percentile(x, 5))
print("95th percentile",np.percentile(x, 95))

5th percentile -3.7735737504366735
95th percentile 6.0552583128613096


## Question:15

### How to find if a given array has any null values?